version: "3.9"
services:
  backend:
    platform: linux/x86_64
    build:
      context: ./backend
      target: dev
    env_file:
      - ./backend/.env.dev
      - ./backend/.env.secret.dev
    stdin_open: true
    tty: true
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails server --binding 0.0.0.0"
    volumes:
      - "./backend:/app"
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  sidekiq:
    platform: linux/x86_64
    build:
      context: ./backend
      target: dev
    env_file:
      - ./backend/.env.dev
      - ./backend/.env.secret.dev
    stdin_open: true
    tty: true
    command: bundle exec sidekiq
    volumes:
      - "./backend:/app"
      - bundle:/bundle
    depends_on:
      - db
      - redis

  db:
    platform: linux/x86_64
    image: "healthcheck/postgres:alpine"
    environment:
      POSTGRES_PASSWORD: db_password

  redis:
    platform: linux/x86_64
    image: "redis:6-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app"
    ports:
      - "3001:3000"
    command: npm start
    environment:
      - NODE_ENV=development

volumes:
  bundle:
  redis:
