name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/adamniedzielski/cat_insurance:${{ github.sha }}
          target: ci
  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/adamniedzielski/cat_insurance:${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
    services:
      postgres:
        image: postgres:16.3-alpine
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    defaults:
      run:
        working-directory: /app

    steps:
      - name: Run Rubocop
        run: |
          bundle exec rubocop
      - name: Run RSpec
        run: |
          bundle exec rake
